name: mmseg
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310haa0f9ac_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.0=hbb29018_2
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=hd590300_0
  - eigen=3.2.8=2
  - expat=2.7.3=h3385a95_0
  - ffmpeg=6.1.1=hecf7045_5
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.12=hc146dc4_1
  - gstreamer=1.24.12=hb6d4d65_1
  - gstreamer-orc=0.4.41=h5eee18b_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.2=h59595ed_0
  - imath=3.1.12=h7955e40_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jasper=2.0.14=hd8c5072_2
  - jpeg=9f=h5ce9db8_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=h3ec8f01_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libass=0.17.3=hba53ac1_1
  - libavif=1.1.1=h0131e85_1
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.4=h77a78f3_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopencv=4.12.0=h06a4308_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - librsvg=2.56.3=hb0330b6_2
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.21=0
  - lz4-c=1.9.4=h6a678d5_1
  - mesalib=25.1.5=h31e3550_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.14.1=py310h41d4191_0
  - numpy-base=2.2.5=py310he1678cf_2
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=py310hc7c50f1_0
  - openexr=3.3.2=hccdc605_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.3=py310h23c847b_1
  - pango=1.54.0=h4c5309f_1
  - pcre2=10.46=hf426167_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.14=h59595ed_0
  - py-opencv=4.12.0=h06a4308_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=py310h06a4308_0
  - qtbase=6.9.2=hd13baf8_5
  - readline=8.3=hc2a1206_0
  - scipy=1.15.3=py310h0a862cd_1
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - svt-av1=2.2.1=h5888daf_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wayland=1.24.0=hdac8c69_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dropblock==0.3.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.4
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - packaging==25.0
      - pillow==11.3.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pyparsing==3.2.5
      - pytorch-wavelets==1.3.0
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - safetensors==0.6.2
      - seaborn==0.13.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sympy==1.14.0
      - thop==0.1.1-2209072238
      - timm==1.0.22
      - torch==2.9.1+cu130
      - torch-geometric==2.7.0
      - torchvision==0.24.1+cu130
      - tqdm==4.67.1
      - triton==3.5.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /root/anaconda3/envs/mmseg
